use_frameworks!

platform :ios, '10.0'

target 'UICommonLayer_Example' do
  pod 'UICommonLayer', :path => '../'

  target 'UICommonLayer_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
